export type NavItem = { href: string; label: string; icon: string; group: string; core?: boolean };
export const NAV: NavItem[] = [
  { href: "/", core: true, label: "Today", icon: "today", group: "Daily" },
  { href: "/attention", core: true, label: "Attention", icon: "attention", group: "Daily" },
  { href: "/inbox", core: true, label: "Inbox intelligence", icon: "inbox", group: "Daily" },
  { href: "/tasks", label: "Tasks and follow-ups", icon: "tasks", group: "Daily" },
  { href: "/deals", core: true, label: "Deals", icon: "deals", group: "Business" },
  { href: "/companies", label: "Companies", icon: "company", group: "Business" },
  { href: "/contacts", core: true, label: "Contacts", icon: "people", group: "Business" },
  { href: "/agencies", label: "Agencies", icon: "agency", group: "Business" },
  { href: "/campaigns", label: "Campaigns", icon: "campaign", group: "Business" },
  { href: "/income", core: true, label: "Income", icon: "chart", group: "Money" },
  { href: "/invoices", core: true, label: "Invoices", icon: "invoice", group: "Money" },
  { href: "/payments", core: true, label: "Payments", icon: "payments", group: "Money" },
  { href: "/revenue", label: "Revenue", icon: "money", group: "Money" },
  { href: "/analytics", label: "Analytics", icon: "chart", group: "Money" },
  { href: "/deliverables", label: "Deliverables", icon: "deliver", group: "Work" },
  { href: "/rights", label: "Usage and exclusivity", icon: "rights", group: "Work" },
  { href: "/documents", label: "Documents", icon: "docs", group: "Work" },
  { href: "/rates", label: "Rate cards", icon: "rate", group: "Work" },
  { href: "/timeline", label: "Timeline", icon: "timeline", group: "Review" },
  { href: "/brief", label: "Daily and weekly brief", icon: "brief", group: "Review" },
  { href: "/quality", label: "Data quality", icon: "quality", group: "Review" },
  { href: "/data", label: "Import and export", icon: "data", group: "Review" },
  { href: "/settings", label: "Settings", icon: "settings", group: "Review" },
];
